CREATE TABLE IF NOT EXISTS `exercises_reference` (
`id` INT AUTO_INCREMENT PRIMARY KEY,
`name_fr` VARCHAR(100) NOT NULL,
`name_en` VARCHAR(100) DEFAULT NULL,
`muscle_group` VARCHAR(50) DEFAULT NULL,
`difficulty` ENUM('debutant', 'intermediaire', 'avance') DEFAULT 'debutant',
`equipment_type` ENUM('poids_du_corps', 'halteres', 'machine', 'barre', 'kettlebell', 'elastique', 'autre') DEFAULT 'poids_du_corps',
`gender` ENUM('male', 'female', 'both') DEFAULT 'both',
`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
INDEX `idx_muscle_group` (`muscle_group`),
INDEX `idx_difficulty` (`difficulty`),
INDEX `idx_equipment` (`equipment_type`),
INDEX `idx_gender` (`gender`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `exercises_reference` (`name_fr`, `name_en`, `muscle_group`, `difficulty`, `equipment_type`, `gender`) VALUES
('Pompes classiques', 'Push-ups', 'pectoraux', 'debutant', 'poids_du_corps', 'both'),
('Pompes diamant', 'Diamond Push-ups', 'pectoraux', 'intermediaire', 'poids_du_corps', 'both'),
('Pompes déclinées', 'Decline Push-ups', 'pectoraux', 'intermediaire', 'poids_du_corps', 'both'),
('Pompes inclinées', 'Incline Push-ups', 'pectoraux', 'debutant', 'poids_du_corps', 'both'),
('Pompes archer', 'Archer Push-ups', 'pectoraux', 'avance', 'poids_du_corps', 'both'),
('Tractions pronation', 'Pull-ups', 'dos', 'intermediaire', 'poids_du_corps', 'both'),
('Tractions supination', 'Chin-ups', 'dos', 'intermediaire', 'poids_du_corps', 'both'),
('Tractions neutres', 'Neutral Grip Pull-ups', 'dos', 'intermediaire', 'poids_du_corps', 'both'),
('Rowing inversé', 'Inverted Rows', 'dos', 'debutant', 'poids_du_corps', 'both'),
('Superman', 'Superman', 'dos', 'debutant', 'poids_du_corps', 'both'),
('Pont fessier', 'Glute Bridge', 'dos', 'debutant', 'poids_du_corps', 'both'),
('Pont une jambe', 'Single Leg Glute Bridge', 'dos', 'intermediaire', 'poids_du_corps', 'both'),
('Pike push-ups', 'Pike Push-ups', 'epaules', 'intermediaire', 'poids_du_corps', 'both'),
('Pompes handstand', 'Handstand Push-ups', 'epaules', 'avance', 'poids_du_corps', 'both'),
('Dips entre chaises', 'Chair Dips', 'epaules', 'debutant', 'poids_du_corps', 'both'),
('T balances', 'T Planks', 'epaules', 'intermediaire', 'poids_du_corps', 'both'),
('Marcheur de mur', 'Wall Walks', 'epaules', 'avance', 'poids_du_corps', 'both'),
('Flexions bras', 'Arm Curls', 'biceps', 'debutant', 'poids_du_corps', 'both'),
('Tractions commando', 'Commando Pull-ups', 'biceps', 'avance', 'poids_du_corps', 'both'),
('Flexions isométriques', 'Isometric Curls', 'biceps', 'intermediaire', 'poids_du_corps', 'both'),
('Extensions triceps', 'Tricep Extensions', 'triceps', 'debutant', 'poids_du_corps', 'both'),
('Pompes triceps', 'Tricep Push-ups', 'triceps', 'intermediaire', 'poids_du_corps', 'both'),
('Dips au sol', 'Floor Dips', 'triceps', 'debutant', 'poids_du_corps', 'both'),
('Squats', 'Squats', 'quadriceps', 'debutant', 'poids_du_corps', 'both'),
('Squat sumo', 'Sumo Squats', 'quadriceps', 'debutant', 'poids_du_corps', 'both'),
('Squat une jambe', 'Pistol Squat', 'quadriceps', 'avance', 'poids_du_corps', 'both'),
('Fentes avant', 'Forward Lunges', 'quadriceps', 'debutant', 'poids_du_corps', 'both'),
('Fentes arrière', 'Reverse Lunges', 'quadriceps', 'debutant', 'poids_du_corps', 'both'),
('Fentes latérales', 'Side Lunges', 'quadriceps', 'intermediaire', 'poids_du_corps', 'both'),
('Fentes bulgares', 'Bulgarian Split Squats', 'quadriceps', 'intermediaire', 'poids_du_corps', 'both'),
('Sissy squat', 'Sissy Squat', 'quadriceps', 'avance', 'poids_du_corps', 'both'),
('Squat sauteur', 'Jump Squats', 'quadriceps', 'intermediaire', 'poids_du_corps', 'both'),
('Good morning', 'Good Morning', 'ischio_jambiers', 'intermediaire', 'poids_du_corps', 'both'),
('Pont nordique', 'Nordic Hamstring Curl', 'ischio_jambiers', 'avance', 'poids_du_corps', 'both'),
('RDL une jambe', 'Single Leg RDL', 'ischio_jambiers', 'intermediaire', 'poids_du_corps', 'both'),
('Extensions mollets', 'Calf Raises', 'mollets', 'debutant', 'poids_du_corps', 'both'),
('Extensions mollets une jambe', 'Single Leg Calf Raises', 'mollets', 'intermediaire', 'poids_du_corps', 'both'),
('Extensions mollets pieds inversés', 'Inverted Calf Raises', 'mollets', 'intermediaire', 'poids_du_corps', 'both'),
('Planche', 'Plank', 'abdominaux', 'debutant', 'poids_du_corps', 'both'),
('Planche latérale', 'Side Plank', 'abdominaux', 'intermediaire', 'poids_du_corps', 'both'),
('Planche dynamique', 'Mountain Climbers', 'abdominaux', 'intermediaire', 'poids_du_corps', 'both'),
('Crunch', 'Crunches', 'abdominaux', 'debutant', 'poids_du_corps', 'both'),
('Crunch inversé', 'Reverse Crunches', 'abdominaux', 'debutant', 'poids_du_corps', 'both'),
('Crunch oblique', 'Oblique Crunches', 'abdominaux', 'intermediaire', 'poids_du_corps', 'both'),
('Lever de jambes', 'Leg Raises', 'abdominaux', 'intermediaire', 'poids_du_corps', 'both'),
('Hollow body', 'Hollow Body Hold', 'abdominaux', 'intermediaire', 'poids_du_corps', 'both'),
('V-ups', 'V-ups', 'abdominaux', 'avance', 'poids_du_corps', 'both'),
('Russian twists', 'Russian Twists', 'abdominaux', 'intermediaire', 'poids_du_corps', 'both'),
('Windshield wipers', 'Windshield Wipers', 'abdominaux', 'avance', 'poids_du_corps', 'both'),
('L-sit', 'L-sit', 'abdominaux', 'avance', 'poids_du_corps', 'both'),
('Flutter kicks', 'Flutter Kicks', 'abdominaux', 'intermediaire', 'poids_du_corps', 'both'),
('Bicycle', 'Bicycle Crunches', 'abdominaux', 'intermediaire', 'poids_du_corps', 'both'),
('Dead bug', 'Dead Bug', 'abdominaux', 'debutant', 'poids_du_corps', 'both'),
('Pont fessier marche', 'Walking Glute Bridge', 'fessiers', 'intermediaire', 'poids_du_corps', 'both'),
('Donkey kicks', 'Donkey Kicks', 'fessiers', 'debutant', 'poids_du_corps', 'both'),
('Fire hydrants', 'Fire Hydrants', 'fessiers', 'debutant', 'poids_du_corps', 'both'),
('Pont fessier une jambe', 'Single Leg Glute Bridge', 'fessiers', 'intermediaire', 'poids_du_corps', 'both'),
('Squat grenouille', 'Frog Squat', 'fessiers', 'intermediaire', 'poids_du_corps', 'both'),
('Burpees', 'Burpees', 'cardio', 'intermediaire', 'poids_du_corps', 'both'),
('Jumping jacks', 'Jumping Jacks', 'cardio', 'debutant', 'poids_du_corps', 'both'),
('High knees', 'High Knees', 'cardio', 'intermediaire', 'poids_du_corps', 'both'),
('Butt kicks', 'Butt Kicks', 'cardio', 'debutant', 'poids_du_corps', 'both'),
('Skaters', 'Skaters', 'cardio', 'intermediaire', 'poids_du_corps', 'both'),
('Jumping lunges', 'Jumping Lunges', 'cardio', 'avance', 'poids_du_corps', 'both'),
('Box jumps sans box', 'Air Box Jumps', 'cardio', 'intermediaire', 'poids_du_corps', 'both'),
('Bear crawls', 'Bear Crawls', 'cardio', 'intermediaire', 'poids_du_corps', 'both'),
('Crab walks', 'Crab Walks', 'cardio', 'intermediaire', 'poids_du_corps', 'both'),
('Inchworms', 'Inchworms', 'cardio', 'intermediaire', 'poids_du_corps', 'both'),
('Ice skaters', 'Ice Skaters', 'cardio', 'intermediaire', 'poids_du_corps', 'both'),
('Développé couché haltères', 'Dumbbell Bench Press', 'pectoraux', 'intermediaire', 'halteres', 'both'),
('Développé incliné haltères', 'Incline Dumbbell Press', 'pectoraux', 'intermediaire', 'halteres', 'both'),
('Développé décliné haltères', 'Decline Dumbbell Press', 'pectoraux', 'intermediaire', 'halteres', 'both'),
('Pec fly haltères', 'Dumbbell Flyes', 'pectoraux', 'intermediaire', 'halteres', 'both'),
('Pec fly incliné', 'Incline Dumbbell Flyes', 'pectoraux', 'intermediaire', 'halteres', 'both'),
('Pullover haltère', 'Dumbbell Pullover', 'pectoraux', 'intermediaire', 'halteres', 'both'),
('Press convergent', 'Dumbbell Squeeze Press', 'pectoraux', 'intermediaire', 'halteres', 'both'),
('Rowing unilatéral', 'Single Arm Dumbbell Row', 'dos', 'debutant', 'halteres', 'both'),
('Rowing haltères', 'Bent Over Dumbbell Row', 'dos', 'intermediaire', 'halteres', 'both'),
('Rowing Arnold', 'Arnold Row', 'dos', 'intermediaire', 'halteres', 'both'),
('Shrugs haltères', 'Dumbbell Shrugs', 'dos', 'debutant', 'halteres', 'both'),
('Deadlift roumain haltères', 'Dumbbell RDL', 'dos', 'intermediaire', 'halteres', 'both'),
('Renegade rows', 'Renegade Rows', 'dos', 'avance', 'halteres', 'both'),
('Deadlift sumo haltères', 'Sumo Dumbbell Deadlift', 'dos', 'intermediaire', 'halteres', 'both'),
('Good morning haltères', 'Dumbbell Good Morning', 'dos', 'intermediaire', 'halteres', 'both'),
('Développé militaire haltères', 'Dumbbell Overhead Press', 'epaules', 'intermediaire', 'halteres', 'both'),
('Développé Arnold', 'Arnold Press', 'epaules', 'intermediaire', 'halteres', 'both'),
('Élévations latérales', 'Lateral Raises', 'epaules', 'debutant', 'halteres', 'both'),
('Élévations frontales', 'Front Raises', 'epaules', 'debutant', 'halteres', 'both'),
('Oiseau', 'Reverse Flyes', 'epaules', 'intermediaire', 'halteres', 'both'),
('Face pulls haltères', 'Dumbbell Face Pulls', 'epaules', 'intermediaire', 'halteres', 'both'),
('Around the world', 'Around the World', 'epaules', 'intermediaire', 'halteres', 'both'),
('Élévations 21s', '21s Lateral Raises', 'epaules', 'intermediaire', 'halteres', 'both'),
('Curl haltères', 'Dumbbell Curls', 'biceps', 'debutant', 'halteres', 'both'),
('Curl marteau', 'Hammer Curls', 'biceps', 'debutant', 'halteres', 'both'),
('Curl concentré', 'Concentration Curls', 'biceps', 'intermediaire', 'halteres', 'both'),
('Curl incliné', 'Incline Dumbbell Curls', 'biceps', 'intermediaire', 'halteres', 'both'),
('Curl spider', 'Spider Curls', 'biceps', 'intermediaire', 'halteres', 'both'),
('Curl alterné', 'Alternating Dumbbell Curls', 'biceps', 'debutant', 'halteres', 'both'),
('Curl 21s', '21s Curls', 'biceps', 'intermediaire', 'halteres', 'both'),
('Curl Zottman', 'Zottman Curls', 'biceps', 'intermediaire', 'halteres', 'both'),
('Extension triceps au-dessus', 'Overhead Tricep Extension', 'triceps', 'debutant', 'halteres', 'both'),
('Extension triceps couché', 'Lying Tricep Extension', 'triceps', 'intermediaire', 'halteres', 'both'),
('Kickback', 'Tricep Kickbacks', 'triceps', 'debutant', 'halteres', 'both'),
('Extension triceps une main', 'Single Arm Overhead Extension', 'triceps', 'debutant', 'halteres', 'both'),
('Floor press triceps', 'Floor Press', 'triceps', 'intermediaire', 'halteres', 'both'),
('Goblet squat', 'Goblet Squat', 'quadriceps', 'debutant', 'halteres', 'both'),
('Fentes haltères', 'Dumbbell Lunges', 'quadriceps', 'intermediaire', 'halteres', 'both'),
('Fentes bulgares haltères', 'Bulgarian Split Squat DB', 'quadriceps', 'intermediaire', 'halteres', 'both'),
('Step-ups haltères', 'Dumbbell Step-ups', 'quadriceps', 'intermediaire', 'halteres', 'both'),
('Squat sumo haltère', 'Sumo Squat DB', 'quadriceps', 'intermediaire', 'halteres', 'both'),
('Deadlift une jambe', 'Single Leg Deadlift', 'ischio_jambiers', 'intermediaire', 'halteres', 'both'),
('Fentes latérales haltères', 'Lateral Lunges DB', 'quadriceps', 'intermediaire', 'halteres', 'both'),
('Extensions mollets haltères', 'Dumbbell Calf Raises', 'mollets', 'debutant', 'halteres', 'both'),
('Hack squat haltères', 'Dumbbell Hack Squat', 'quadriceps', 'intermediaire', 'halteres', 'both'),
('Sissy squat haltère', 'Sissy Squat DB', 'quadriceps', 'avance', 'halteres', 'both'),
('Man makers', 'Man Makers', 'full_body', 'avance', 'halteres', 'both'),
('Devil press', 'Devil Press', 'full_body', 'avance', 'halteres', 'both'),
('Thrusters', 'Dumbbell Thrusters', 'full_body', 'intermediaire', 'halteres', 'both'),
('Clean and press', 'Dumbbell Clean and Press', 'full_body', 'avance', 'halteres', 'both'),
('Snatch haltère', 'Dumbbell Snatch', 'full_body', 'avance', 'halteres', 'both'),
('Turkish get-up', 'Turkish Get-Up', 'full_body', 'avance', 'halteres', 'both'),
('Farmers walk', 'Farmers Walk', 'full_body', 'debutant', 'halteres', 'both'),
('Waiter walk', 'Waiter Walk', 'full_body', 'intermediaire', 'halteres', 'both'),
('Suitcase carry', 'Suitcase Carry', 'full_body', 'intermediaire', 'halteres', 'both'),
('Développé machine', 'Machine Chest Press', 'pectoraux', 'debutant', 'machine', 'both'),
('Butterfly / Pec deck', 'Pec Deck Fly', 'pectoraux', 'debutant', 'machine', 'both'),
('Développé convergent', 'Converging Chest Press', 'pectoraux', 'debutant', 'machine', 'both'),
('Presse à bras', 'Seated Chest Press', 'pectoraux', 'debutant', 'machine', 'both'),
('Tirage vertical', 'Lat Pulldown', 'dos', 'debutant', 'machine', 'both'),
('Tirage vertical prise serrée', 'Close Grip Pulldown', 'dos', 'debutant', 'machine', 'both'),
('Rowing assis', 'Seated Cable Row', 'dos', 'debutant', 'machine', 'both'),
('Rowing unilatéral machine', 'Single Arm Row Machine', 'dos', 'debutant', 'machine', 'both'),
('Tirage horizontal', 'Horizontal Pulldown', 'dos', 'debutant', 'machine', 'both'),
('Pullover machine', 'Machine Pullover', 'dos', 'intermediaire', 'machine', 'both'),
('Hyperextension', 'Back Extension', 'dos', 'debutant', 'machine', 'both'),
('Presse à cuisses', 'Leg Press', 'quadriceps', 'debutant', 'machine', 'both'),
('Presse à cuisses horizontale', 'Horizontal Leg Press', 'quadriceps', 'debutant', 'machine', 'both'),
('Hack squat machine', 'Hack Squat Machine', 'quadriceps', 'intermediaire', 'machine', 'both'),
('Squat V', 'V-Squat', 'quadriceps', 'intermediaire', 'machine', 'both'),
('Squat pendulum', 'Pendulum Squat', 'quadriceps', 'intermediaire', 'machine', 'both'),
('Leg extension', 'Leg Extension', 'quadriceps', 'debutant', 'machine', 'both'),
('Leg curl allongé', 'Lying Leg Curl', 'ischio_jambiers', 'debutant', 'machine', 'both'),
('Leg curl assis', 'Seated Leg Curl', 'ischio_jambiers', 'debutant', 'machine', 'both'),
('Leg curl debout', 'Standing Leg Curl', 'ischio_jambiers', 'debutant', 'machine', 'both'),
('Presse mollets', 'Calf Press', 'mollets', 'debutant', 'machine', 'both'),
('Machine à mollets', 'Calf Raise Machine', 'mollets', 'debutant', 'machine', 'both'),
('Mollets assis machine', 'Seated Calf Raise', 'mollets', 'debutant', 'machine', 'both'),
('Adducteurs', 'Hip Adduction', 'adducteurs', 'debutant', 'machine', 'both'),
('Abducteurs', 'Hip Abduction', 'abducteurs', 'debutant', 'machine', 'both'),
('Hip thrust machine', 'Machine Hip Thrust', 'fessiers', 'intermediaire', 'machine', 'both'),
('Glute kickback', 'Glute Kickback Machine', 'fessiers', 'debutant', 'machine', 'both'),
('Sissy squat machine', 'Sissy Squat Machine', 'quadriceps', 'intermediaire', 'machine', 'both'),
('Smith machine squat', 'Smith Machine Squat', 'quadriceps', 'intermediaire', 'machine', 'both'),
('Développé machine', 'Machine Shoulder Press', 'epaules', 'debutant', 'machine', 'both'),
('Développé Arnold machine', 'Arnold Press Machine', 'epaules', 'intermediaire', 'machine', 'both'),
('Élévations latérales machine', 'Machine Lateral Raise', 'epaules', 'debutant', 'machine', 'both'),
('Oiseau machine', 'Reverse Pec Deck', 'epaules', 'debutant', 'machine', 'both'),
('Élévations frontales machine', 'Machine Front Raise', 'epaules', 'debutant', 'machine', 'both'),
('Shrugs machine', 'Machine Shrugs', 'epaules', 'debutant', 'machine', 'both'),
('Face pulls machine', 'Face Pull Machine', 'epaules', 'debutant', 'machine', 'both'),
('Tapis de course', 'Treadmill', 'cardio', 'debutant', 'machine', 'both'),
('Vélo droit', 'Stationary Bike', 'cardio', 'debutant', 'machine', 'both'),
('Vélo allongé', 'Recumbent Bike', 'cardio', 'debutant', 'machine', 'both'),
('Rameur', 'Rowing Machine', 'cardio', 'intermediaire', 'machine', 'both'),
('Elliptique', 'Elliptical', 'cardio', 'debutant', 'machine', 'both'),
('Stepper', 'Stepper', 'cardio', 'debutant', 'machine', 'both'),
('Escalier mécanique', 'StairMaster', 'cardio', 'intermediaire', 'machine', 'both'),
('SkiErg', 'SkiErg', 'cardio', 'intermediaire', 'machine', 'both'),
('Air bike', 'Air Bike', 'cardio', 'intermediaire', 'machine', 'both'),
('Curve treadmill', 'Curve Treadmill', 'cardio', 'avance', 'machine', 'both'),
('Développé couché', 'Barbell Bench Press', 'pectoraux', 'intermediaire', 'barre', 'both'),
('Développé incliné', 'Incline Bench Press', 'pectoraux', 'intermediaire', 'barre', 'both'),
('Développé décliné', 'Decline Bench Press', 'pectoraux', 'intermediaire', 'barre', 'both'),
('Développé serré', 'Close Grip Bench Press', 'pectoraux', 'intermediaire', 'barre', 'both'),
('Développé prise large', 'Wide Grip Bench Press', 'pectoraux', 'intermediaire', 'barre', 'both'),
('Développé pauses', 'Paused Bench Press', 'pectoraux', 'avance', 'barre', 'both'),
('Développé floor press', 'Floor Press', 'pectoraux', 'intermediaire', 'barre', 'both'),
('Soulevé de terre', 'Deadlift', 'dos', 'intermediaire', 'barre', 'both'),
('Soulevé de terre roumain', 'Romanian Deadlift', 'dos', 'intermediaire', 'barre', 'both'),
('Soulevé de terre sumo', 'Sumo Deadlift', 'dos', 'intermediaire', 'barre', 'both'),
('Rowing barre', 'Barbell Row', 'dos', 'intermediaire', 'barre', 'both'),
('Rowing supination', 'Underhand Barbell Row', 'dos', 'intermediaire', 'barre', 'both'),
('Rowing Yates', 'Yates Row', 'dos', 'intermediaire', 'barre', 'both'),
('Shrugs barre', 'Barbell Shrugs', 'dos', 'debutant', 'barre', 'both'),
('Power clean', 'Power Clean', 'dos', 'avance', 'barre', 'both'),
('Clean and jerk', 'Clean and Jerk', 'dos', 'avance', 'barre', 'both'),
('Snatch', 'Snatch', 'dos', 'avance', 'barre', 'both'),
('Good morning barre', 'Barbell Good Morning', 'dos', 'avance', 'barre', 'both'),
('T-bar row', 'T-Bar Row', 'dos', 'intermediaire', 'barre', 'both'),
('Meadows row', 'Meadows Row', 'dos', 'avance', 'barre', 'both'),
('Développé militaire', 'Overhead Press', 'epaules', 'intermediaire', 'barre', 'both'),
('Développé assis', 'Seated Military Press', 'epaules', 'intermediaire', 'barre', 'both'),
('Développé behind neck', 'Behind the Neck Press', 'epaules', 'avance', 'barre', 'both'),
('Push press', 'Push Press', 'epaules', 'intermediaire', 'barre', 'both'),
('Jerk', 'Jerk', 'epaules', 'avance', 'barre', 'both'),
('Upright row', 'Upright Row', 'epaules', 'intermediaire', 'barre', 'both'),
('High pull', 'High Pull', 'epaules', 'avance', 'barre', 'both'),
('Landmine press', 'Landmine Press', 'epaules', 'intermediaire', 'barre', 'both'),
('Squat', 'Barbell Squat', 'quadriceps', 'intermediaire', 'barre', 'both'),
('Squat avant', 'Front Squat', 'quadriceps', 'avance', 'barre', 'both'),
('Squat box', 'Box Squat', 'quadriceps', 'intermediaire', 'barre', 'both'),
('Squat pause', 'Paused Squat', 'quadriceps', 'avance', 'barre', 'both'),
('Squat jump', 'Jump Squat', 'quadriceps', 'avance', 'barre', 'both'),
('Squat bulgare barre', 'Bulgarian Split Squat BB', 'quadriceps', 'avance', 'barre', 'both'),
('Fentes barre', 'Barbell Lunges', 'quadriceps', 'intermediaire', 'barre', 'both'),
('Fentes arrière barre', 'Reverse Barbell Lunges', 'quadriceps', 'intermediaire', 'barre', 'both'),
('Fentes latérales barre', 'Lateral Barbell Lunges', 'quadriceps', 'avance', 'barre', 'both'),
('Good morning', 'Good Morning', 'ischio_jambiers', 'avance', 'barre', 'both'),
('Hip thrust barre', 'Barbell Hip Thrust', 'fessiers', 'intermediaire', 'barre', 'both'),
('Step-ups barre', 'Barbell Step-ups', 'quadriceps', 'intermediaire', 'barre', 'both'),
('Hack squat barre', 'Barbell Hack Squat', 'quadriceps', 'intermediaire', 'barre', 'both'),
('Zercher squat', 'Zercher Squat', 'quadriceps', 'avance', 'barre', 'both'),
('Overhead squat', 'Overhead Squat', 'quadriceps', 'avance', 'barre', 'both'),
('Jefferson squat', 'Jefferson Squat', 'quadriceps', 'avance', 'barre', 'both'),
('Anderson squat', 'Anderson Squat', 'quadriceps', 'avance', 'barre', 'both'),
('Squat pin', 'Pin Squat', 'quadriceps', 'avance', 'barre', 'both'),
('Hatfield squat', 'Hatfield Squat', 'quadriceps', 'intermediaire', 'barre', 'both'),
('Safety bar squat', 'Safety Bar Squat', 'quadriceps', 'intermediaire', 'barre', 'both'),
('Tirage élastique', 'Band Pull Apart', 'epaules', 'debutant', 'elastique', 'both'),
('Face pull élastique', 'Band Face Pull', 'epaules', 'debutant', 'elastique', 'both'),
('Press élastique', 'Band Press', 'pectoraux', 'debutant', 'elastique', 'both'),
('Fly élastique', 'Band Fly', 'pectoraux', 'debutant', 'elastique', 'both'),
('Rowing élastique', 'Band Row', 'dos', 'debutant', 'elastique', 'both'),
('Pull apart élastique', 'Band Pull Apart', 'dos', 'debutant', 'elastique', 'both'),
('Curl élastique', 'Band Curl', 'biceps', 'debutant', 'elastique', 'both'),
('Extension triceps élastique', 'Band Tricep Extension', 'triceps', 'debutant', 'elastique', 'both'),
('Élévations élastique', 'Band Lateral Raise', 'epaules', 'debutant', 'elastique', 'both'),
('Squat élastique', 'Band Squat', 'quadriceps', 'debutant', 'elastique', 'both'),
('Fentes élastique', 'Band Lunges', 'quadriceps', 'debutant', 'elastique', 'both'),
('Extensions mollets élastique', 'Band Calf Raises', 'mollets', 'debutant', 'elastique', 'both'),
('Crunch élastique', 'Band Crunch', 'abdominaux', 'debutant', 'elastique', 'both'),
('Rotation russe élastique', 'Band Russian Twist', 'abdominaux', 'intermediaire', 'elastique', 'both'),
('Monster walk', 'Monster Walk', 'fessiers', 'debutant', 'elastique', 'both'),
('Clamshell élastique', 'Banded Clamshell', 'fessiers', 'debutant', 'elastique', 'both'),
('Hip thrust élastique', 'Banded Hip Thrust', 'fessiers', 'debutant', 'elastique', 'both'),
('Good morning élastique', 'Band Good Morning', 'ischio_jambiers', 'debutant', 'elastique', 'both'),
('Deadlift élastique', 'Band Deadlift', 'dos', 'debutant', 'elastique', 'both'),
('Pompes élastique', 'Banded Push-ups', 'pectoraux', 'intermediaire', 'elastique', 'both'),
('Traction assistée élastique', 'Assisted Pull-up', 'dos', 'debutant', 'elastique', 'both'),
('Dips assistés élastique', 'Assisted Dips', 'pectoraux', 'debutant', 'elastique', 'both'),
('Muscle-up élastique', 'Assisted Muscle-up', 'dos', 'avance', 'elastique', 'both'),
('Swing deux mains', 'Two-Handed Kettlebell Swing', 'fessiers', 'debutant', 'kettlebell', 'both'),
('Swing une main', 'One-Handed Kettlebell Swing', 'fessiers', 'intermediaire', 'kettlebell', 'both'),
('Swing alterné', 'Alternating Kettlebell Swing', 'fessiers', 'intermediaire', 'kettlebell', 'both'),
('Goblet squat kettlebell', 'Kettlebell Goblet Squat', 'quadriceps', 'debutant', 'kettlebell', 'both'),
('Clean kettlebell', 'Kettlebell Clean', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Press kettlebell', 'Kettlebell Press', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Clean and press kettlebell', 'Kettlebell Clean and Press', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Snatch kettlebell', 'Kettlebell Snatch', 'epaules', 'avance', 'kettlebell', 'both'),
('Rowing kettlebell', 'Kettlebell Row', 'dos', 'intermediaire', 'kettlebell', 'both'),
('Farmers walk kettlebell', 'Kettlebell Farmers Walk', 'full_body', 'debutant', 'kettlebell', 'both'),
('Overhead walk kettlebell', 'Kettlebell Overhead Walk', 'full_body', 'intermediaire', 'kettlebell', 'both'),
('Rack walk kettlebell', 'Kettlebell Rack Walk', 'full_body', 'intermediaire', 'kettlebell', 'both'),
('Deadlift kettlebell', 'Kettlebell Deadlift', 'dos', 'debutant', 'kettlebell', 'both'),
('Sumo deadlift kettlebell', 'Kettlebell Sumo Deadlift', 'dos', 'debutant', 'kettlebell', 'both'),
('Single leg deadlift kettlebell', 'Kettlebell Single Leg Deadlift', 'dos', 'intermediaire', 'kettlebell', 'both'),
('Figure 8', 'Figure 8', 'core', 'intermediaire', 'kettlebell', 'both'),
('Around the body', 'Around the Body Pass', 'core', 'debutant', 'kettlebell', 'both'),
('Halo', 'Halo', 'epaules', 'debutant', 'kettlebell', 'both'),
('Arm bar', 'Arm Bar', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Windmill', 'Windmill', 'full_body', 'avance', 'kettlebell', 'both'),
('Pistol squat kettlebell', 'Kettlebell Pistol Squat', 'quadriceps', 'avance', 'kettlebell', 'both'),
('Lunge press kettlebell', 'Kettlebell Lunge Press', 'full_body', 'intermediaire', 'kettlebell', 'both'),
('High pull kettlebell', 'Kettlebell High Pull', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Push press kettlebell', 'Kettlebell Push Press', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Jerk kettlebell', 'Kettlebell Jerk', 'epaules', 'avance', 'kettlebell', 'both'),
('Thrusters kettlebell', 'Kettlebell Thrusters', 'full_body', 'intermediaire', 'kettlebell', 'both'),
('Renegade rows kettlebell', 'Kettlebell Renegade Rows', 'dos', 'avance', 'kettlebell', 'both'),
('Man makers kettlebell', 'Kettlebell Man Makers', 'full_body', 'avance', 'kettlebell', 'both'),
('Devil press kettlebell', 'Kettlebell Devil Press', 'full_body', 'avance', 'kettlebell', 'both'),
('Deck squat', 'Deck Squat', 'full_body', 'intermediaire', 'kettlebell', 'both'),
('Bottom-up press', 'Bottom-Up Press', 'epaules', 'avance', 'kettlebell', 'both'),
('Sots press', 'Sots Press', 'epaules', 'avance', 'kettlebell', 'both'),
('Bent press', 'Bent Press', 'full_body', 'avance', 'kettlebell', 'both'),
('See-saw press', 'See-Saw Press', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Double clean', 'Double Kettlebell Clean', 'epaules', 'avance', 'kettlebell', 'both'),
('Double press', 'Double Kettlebell Press', 'epaules', 'avance', 'kettlebell', 'both'),
('Double front squat', 'Double Kettlebell Front Squat', 'quadriceps', 'avance', 'kettlebell', 'both'),
('Double swing', 'Double Kettlebell Swing', 'fessiers', 'avance', 'kettlebell', 'both'),
('Alternating clean', 'Alternating Kettlebell Clean', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Alternating press', 'Alternating Kettlebell Press', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Alternating swing', 'Alternating Kettlebell Swing', 'fessiers', 'intermediaire', 'kettlebell', 'both'),
('Single arm swing', 'Single Arm Kettlebell Swing', 'fessiers', 'intermediaire', 'kettlebell', 'both'),
('Single arm clean', 'Single Arm Kettlebell Clean', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Single arm press', 'Single Arm Kettlebell Press', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Single arm snatch', 'Single Arm Kettlebell Snatch', 'epaules', 'avance', 'kettlebell', 'both'),
('Single arm swing switch', 'Single Arm Swing Switch', 'fessiers', 'intermediaire', 'kettlebell', 'both'),
('Russian twist kettlebell', 'Kettlebell Russian Twist', 'abdominaux', 'intermediaire', 'kettlebell', 'both'),
('Sit-up kettlebell', 'Kettlebell Sit-Up', 'abdominaux', 'intermediaire', 'kettlebell', 'both'),
('Leg raise kettlebell', 'Kettlebell Leg Raise', 'abdominaux', 'intermediaire', 'kettlebell', 'both'),
('Plank pull-through', 'Kettlebell Plank Pull-Through', 'abdominaux', 'intermediaire', 'kettlebell', 'both'),
('Squat hold', 'Kettlebell Squat Hold', 'quadriceps', 'intermediaire', 'kettlebell', 'both'),
('Overhead hold', 'Kettlebell Overhead Hold', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Rack hold', 'Kettlebell Rack Hold', 'epaules', 'debutant', 'kettlebell', 'both'),
('Bottoms-up carry', 'Bottoms-Up Carry', 'epaules', 'avance', 'kettlebell', 'both'),
('Waiter carry', 'Waiter Carry', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Racked carry', 'Racked Carry', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Overhead carry', 'Overhead Carry', 'epaules', 'intermediaire', 'kettlebell', 'both'),
('Suitcase carry', 'Suitcase Carry', 'core', 'intermediaire', 'kettlebell', 'both'),
('Goblet carry', 'Goblet Carry', 'core', 'debutant', 'kettlebell', 'both'),
('Partner drags', 'Kettlebell Partner Drags', 'full_body', 'avance', 'kettlebell', 'both'),
('Sled pull', 'Kettlebell Sled Pull', 'full_body', 'intermediaire', 'kettlebell', 'both'),
('Floor press kettlebell', 'Kettlebell Floor Press', 'pectoraux', 'intermediaire', 'kettlebell', 'both'),
('Skullcrusher kettlebell', 'Kettlebell Skullcrusher', 'triceps', 'intermediaire', 'kettlebell', 'both'),
('Pullover kettlebell', 'Kettlebell Pullover', 'pectoraux', 'intermediaire', 'kettlebell', 'both'),
('Fly floor', 'Kettlebell Floor Fly', 'pectoraux', 'intermediaire', 'kettlebell', 'both'),
('Crush curl', 'Kettlebell Crush Curl', 'biceps', 'intermediaire', 'kettlebell', 'both'),
('Towel curl', 'Kettlebell Towel Curl', 'biceps', 'intermediaire', 'kettlebell', 'both'),
('Inverted row kettlebell', 'Kettlebell Inverted Row', 'dos', 'intermediaire', 'kettlebell', 'both'),
('Pull-up kettlebell', 'Kettlebell Pull-up', 'dos', 'avance', 'kettlebell', 'both'),
('Dip kettlebell', 'Kettlebell Dip', 'pectoraux', 'avance', 'kettlebell', 'both'),
('Muscle-up kettlebell', 'Kettlebell Muscle-Up', 'full_body', 'avance', 'kettlebell', 'both'),
('Handstand push-up kettlebell', 'Kettlebell Handstand Push-up', 'epaules', 'avance', 'kettlebell', 'both'),
('Turkish get-up', 'Turkish Get-Up', 'full_body', 'avance', 'kettlebell', 'both');